# Generated by Django 5.2.9 on 2026-01-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebateRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('ai_position', models.TextField()),
                ('research_summary', models.JSONField(default=dict)),
                ('current_round', models.IntegerField(default=1)),
                ('round_type', models.CharField(choices=[('ai_opening', 'AI Opening Position'), ('user_response', 'User Response'), ('ai_counter', 'AI Counter Argument')], default='ai_opening', max_length=20)),
                ('conversation', models.JSONField(default=list)),
                ('ai_feedbacks', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('overall_score', models.FloatField(default=0.0)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('user_argument', models.TextField()),
                ('ai_feedback', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
