# Generated by Django 5.2.9 on 2026-01-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='debateround',
            index=models.Index(fields=['session_id'], name='trainer_deb_session_525c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='debateround',
            index=models.Index(fields=['-created_at'], name='trainer_deb_created_f68924_idx'),
        ),
        migrations.AddIndex(
            model_name='debateround',
            index=models.Index(fields=['user_name', '-created_at'], name='trainer_deb_user_na_bf4a60_idx'),
        ),
        migrations.AddIndex(
            model_name='debateround',
            index=models.Index(fields=['is_active', '-created_at'], name='trainer_deb_is_acti_f7a8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='debatesession',
            index=models.Index(fields=['-created_at'], name='trainer_deb_created_37affb_idx'),
        ),
        migrations.AddIndex(
            model_name='debatesession',
            index=models.Index(fields=['user_name', '-created_at'], name='trainer_deb_user_na_a65de1_idx'),
        ),
    ]
