# Generated by Django 5.2.9 on 2026-01-20 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_debateround_trainer_deb_session_525c0d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalDebateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(choices=[('custom', 'Custom'), ('parliamentary', 'Parliamentary (4v4)'), ('public_forum', 'Public Forum (2v2)'), ('world_schools', 'World Schools (3v3)')], default='custom', max_length=20)),
                ('motion', models.TextField()),
                ('is_affirmative', models.BooleanField(default=True)),
                ('speakers_per_side', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('substantive_speech_time', models.IntegerField(default=480, help_text='Duration of substantive speeches in seconds', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(3600)])),
                ('reply_speech_time', models.IntegerField(default=240, help_text='Duration of reply speeches in seconds', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1200)])),
                ('protected_time', models.IntegerField(default=60, help_text='Protected time at start (no POI) in seconds', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600)])),
                ('include_replies', models.BooleanField(default=True)),
                ('allow_poi', models.BooleanField(default=True, help_text='Allow Points of Information')),
                ('poi_duration', models.IntegerField(default=15, help_text='Duration of each POI in seconds', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('max_pois_per_speech', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('no_new_arguments_in_rebuttal', models.BooleanField(default=True)),
                ('require_definitions', models.BooleanField(default=False)),
                ('require_respect', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormalDebateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_side', models.CharField(choices=[('affirmative', 'Affirmative'), ('negative', 'Negative')], max_length=20)),
                ('ai_side', models.CharField(choices=[('affirmative', 'Affirmative'), ('negative', 'Negative')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20)),
                ('current_speaker_index', models.IntegerField(default=0)),
                ('current_speech_time_elapsed', models.IntegerField(default=0)),
                ('speeches', models.JSONField(default=list)),
                ('pois_given', models.JSONField(default=list)),
                ('pois_received', models.JSONField(default=list)),
                ('user_score', models.FloatField(default=0.0)),
                ('ai_score', models.FloatField(default=0.0)),
                ('feedback', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.formaldebateconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='trainer_for_session_5e5e5b_idx'), models.Index(fields=['user_name', '-created_at'], name='trainer_for_user_na_bdb29f_idx'), models.Index(fields=['status'], name='trainer_for_status_48d3b8_idx')],
            },
        ),
    ]
