# Generated by Django 5.2.9 on 2026-03-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_formaldebateconfig_formaldebatesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('total_debates', models.IntegerField(default=0)),
                ('debates_won', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('highest_score', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_debate_date', models.DateField(blank=True, null=True)),
                ('badges', models.JSONField(default=list)),
                ('daily_challenge_completed', models.BooleanField(default=False)),
                ('daily_challenge_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-xp'],
                'indexes': [models.Index(fields=['-xp'], name='trainer_use_xp_a5ae29_idx'), models.Index(fields=['user_name'], name='trainer_use_user_na_50f326_idx')],
            },
        ),
    ]
